<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="dayalan-Latitude-E6430" failures="2" tests="19" name="Default test" time="80.272" errors="0" timestamp="2023-06-29T13:17:48 IST">
  <testcase classname="TVT.TVT.Title" name="login" time="50.246"/>
  <testcase classname="TVT.TVT.Title" name="CreateProject" time="3.22"/>
  <testcase classname="TVT.TVT.Title" name="OriginalUpload" time="0.444"/>
  <testcase classname="TVT.TVT.Title" name="CopyUpload" time="0.091"/>
  <testcase classname="TVT.TVT.Title" name="cartonsClicked" time="2.978"/>
  <testcase classname="TVT.TVT.Title" name="cartonswithclonesClicked" time="0.397"/>
  <testcase classname="TVT.TVT.Title" name="cartonsqrdhuman" time="0.522"/>
  <testcase classname="TVT.TVT.Title" name="cartonsqrdveterinary" time="0.535"/>
  <testcase classname="TVT.TVT.Title" name="Documents" time="0.57"/>
  <testcase classname="TVT.TVT.Title" name="Documents_Complex_Languages" time="0.554"/>
  <testcase classname="TVT.TVT.Title" name="Documents_without_hyphenation_check" time="0.569"/>
  <testcase classname="TVT.TVT.Title" name="Leaflets_Complex_Languages" time="0.55"/>
  <testcase classname="TVT.TVT.Title" name="Leaflets" time="0.591"/>
  <testcase classname="TVT.TVT.Title" name="LeafletswithspecialPDFs" time="0.701"/>
  <testcase classname="TVT.TVT.Title" name="addfile" time="0.506"/>
  <testcase classname="TVT.TVT.Title" name="tick" time="2.565"/>
  <testcase classname="TVT.TVT.Title" name="compare" time="13.73">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Words count have difference expected [102] but found [1156]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Words count have difference expected [102] but found [1156]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at TVT.TVT.Title.compare(Title.java:391)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- compare -->
  <testcase classname="TVT.TVT.Title" name="check" time="0.224"/>
  <testcase classname="TVT.TVT.Title" name="Compare_Results" time="0.383">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Deviation found expected [Text deviation: 0] but found [Text deviation: 10]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Deviation found expected [Text deviation: 0] but found [Text deviation: 10]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at TVT.TVT.Title.Compare_Results(Title.java:482)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Compare_Results -->
  <testcase classname="TVT.TVT.Title" name="projectclose" time="0.0">
    <ignored/>
  </testcase> <!-- projectclose -->
  <testcase classname="TVT.TVT.Title" name="smallarrowcopy" time="0.0">
    <ignored/>
  </testcase> <!-- smallarrowcopy -->
  <testcase classname="TVT.TVT.Title" name="smallarroworiginal" time="0.0">
    <ignored/>
  </testcase> <!-- smallarroworiginal -->
</testsuite> <!-- Default test -->
